version: "2"
services:
  mongodb:
    container_name: some-mongo-airline
    image: mongo:latest
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/data/db
    ports:
      - 27017:27017
    command: mongod --smallfiles --logpath=/dev/null # --quiet

  app:
    build: .
    working_dir: .
    volumes:
      - ./app:/app
      - ~/.m2:/root/.m2
    expose:
      - "8080"
#    command: mvn clean spring-boot:run
    depends_on:
      - mongodb

