version: '2.1'
services:
  mongodb:
    image: mongo:latest
    hostname: "mongodb"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/data/db
    ports:
      - 27017:27017
    networks:
      - appdata_airline-net

networks:
  appdata_airline-net:
    external: true